version: '3'
services:
    mysql:
        image: mysql:latest
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=user
            - MYSQL_DATABASE=student
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 2s
            retries: 5
        volumes:
            - ./db_init/:/docker-entrypoint-initdb.d/

    phpmyadmin:
        depends_on:
            mysql:
                condition: service_healthy
        image: phpmyadmin
        restart: always
        ports:
            - "8090:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: password
